### ISSUE TITLE
Intellij + gradle = no scala sdk

### ISSUE THREAD

**Issue by z4f1r0v** [playframework/play-scala-rest-api-example#111]
I want to use the project with the gradle build. Unfortunately every time I reload the `build.gradle` file, Intellij _forgets_ the path to the scala sdk. Thus no sources can be read, no color coding is made, ... 

Here is the error I get in the console:

```
Warning root project 'play-scala-rest-api-example': Unable to build Scala project configuration
Details: org.gradle.api.GradleException: Cannot infer Scala class path because no Scala library Jar was found. Does root project 'play-scala-rest-api-example' declare dependency to scala-library? Searched classpath: file collection.
```

I have removed everything related to sbt.

Have you had problems like these when you added the gradle related code to the project?
Any ideas what could be done to overcome this?

Thanks

**Comment by z4f1r0v** [comment]
Seems like too big of a hassle. Going for sbt. Closing.

**Comment by marcospereira** [comment]
Hi @alexanderzafirov, maybe you should report this to Intellij? Since the project works when running Gradle directly, I suspect this is a problem with Gradle support in IDEA.

Best.
